### PR TITLE
Add support for more models in ProBook/EliteBook 6x70/8x70 series

### PR DESCRIPTION
**Pull request by datagutten**
Moved existing model config to shared folder and added more models which use the same BIOS

### CODE REVIEW

**Comment by datagutten** [comment]
I am planning to use BiosSledgehammer when rolling out Windows 10 at work, so I am testing and adding all models we have.

**Comment by texhex** [comment]
Thanks, I would be happy to add them. But I would prefer that models, that share the same BIOS version should also share the BIOS-Settings.txt. Is there any special reason not to define them as Shared as well?

**Comment by datagutten** [comment]
The current BIOS settings for HP EliteBook 8570p sets "Virtualization Technology for Directed I/O (VTd)" to disabled with the comment "Might cause issues with the GPU", but I have not tested if that applies to the other models too or if it should be enabled there.

**Comment by texhex** [comment]
If you search for "intel graphics iommu issues hyper v", there are several reports that VTd and Intel GPUs can go bonkers in case Hyper-V is involved. Since Hyper-V is used often for several Windows 10 features like Device Guard - Credential Guard or Application Guard it was decided to disable VT-d by default. 

Based on that information, could you consider merging those separate BIOS settings into shared ones?

**Comment by datagutten** [comment]
Common BIOS settings added in commit 29627e4.
Is VTd a common cause of trouble? I got some ProBook 430 G3 which won't boot if I enable it.

**Comment by texhex** [comment]
Thanks, will merge in a second. 

I have never used a 430 G3 but it's uncommon that VTd prevents booting. If this has anything to do with the VTd vs. Intel GFX problem, you should check if your domain settings enable Hyper V or any feature that depends on it. 

Beside that, I'm only aware of G1 devices having somethings boot issues when UEFI + Secure Boot is installed. The very first boot after activating this option usually fails and the device requires a full power cycle. After that, it works as expected.

**Pull request merged**
