### PR TITLE
Add support for more models

### PR DESCRIPTION
**Pull request by datagutten**

### CODE REVIEW

**Comment by texhex** [comment]
Thanks @datagutten, awesome that you add so many models again! 

However, I have an issue with the removal of the SGX setting for the EliteBook G4, because that setting is valid for G4 devices with vPro. Is it possible that you have devices without vPro? 

I checked with several other admins that I know and they buy devices with vPro, so I would like to keep that setting as I think that is the, somewhat, standard.

**Comment by datagutten** [comment]
I don't know how to tell if my model has vPro or not, according to Intel's website the CPU has support for SGX, but the option for it is not present in BIOS.
The SKU for my model is similar to the sample SKU for a model without vPro in Readme.md, so I re-added the setting to the generic model folder and made a SKU specific folder without it.

**Comment by texhex** [comment]
Thank you! I will do the merge shortly.

In order to find out if a device has vPro I could think off two options: Number one is to check for "vPro" or "Intel AMT" stickers on the devices, I believe the OEMs are forced to put them on the device when they are using the vPro technology. 

If the device has no sticker (a lot of users hate it and remove them), you could try to use GetAllBiosSettings.bat from the \BCU folder to check the settings of the device. If I remember it correctly, some boot options name the NIC based on if the device is vPro or not - e.g. "Intel XXX-Non-vPro" or something like that. I can't remember it exactly, this was some time ago. 

Just my 2C: If you are using a SKU folder, please think about creating a TXT file in that folder to describe for which model it is exactly. In case you need to update the folder in a few months, you will no longer remember what that 7 digit SKU code stands for.

**Comment by texhex** [comment]
@datagutten FYI: I updated the SPDownload.txt files in Shared\HP ProBook 4x0 G3\ to use https://

**Comment by texhex** [comment]
@datagutten I was able to find the old docs regarding vPro and Non-vPro. You can detect by checking the *HBMA Priority List* setting:

```
HBMA Priority List
	USB NIC Dongle:HP External Adapter :XXXX
        ....
	Embedded NIC:Intel (non-vPro) :XXXXX(Disabled)
```

If the device has vPro, the NIC is named *Embedded NIC:Intel (vPro)*

**Pull request merged**
