### PR TITLE
Updates and deduplication

### PR DESCRIPTION
**Pull request by datagutten**
I discovered that some models were using ME updates that already existed in shared folders, so I added references to the shared folders and removed the updates from the model folders.
EliteBook Folio 9470m and Pro x2 612 G2 had two BIOS versions, I removed both and added a new version.
I also added support for HP ProBook 4x0 G4 and G5.

Now my working dir is clean and I am going on vacation.

### CODE REVIEW

**Comment by texhex** [comment]
Thanks for the effort, but I have to admit that I do not like the idea that a ZBook gets its ME update from a ProBook 6x0 G1. Of course, it is possible but is it also understandable by the operator? I doubt so. 

For example, if I would update the ME files in the shared folder "HP EliteBook 8xx G1", I would not expect this to have an effect for a ZBook. I really see an benefit of this deduplication in terms of storage and update effort, but for any other operator not aware of the dependencies I fear this to cause confusion.

It would be perfectly fine if we could create one shared folder that is able to "group" those ME in a way an operator directly understands the dependencies. 

Given that you are on your way to your vacation, I will most likely merge this PR but revert the changes for the ZBooks. 

Enjoy your vacation!

**Comment by datagutten** [comment]
I see the problem. What about renaming "HP ProBook 6x0 G1" to "HP ProBook 6x0 G1-HP ZBook 1x G2"?
This could work for some of the other models too, but I see that the compatibility of sp82486 in "HP ZBook 1x G4" should be taken a closer look at, according to the release notes it supports a lot of models, but it doesn't specify which generation.

**Comment by texhex** [comment]
To be honest, the folder name *HP ProBook 6x0 G1-HP ZBook 1x G2* looks a little bit frankensteined and as far as I understood it, that would only share the ME updates, but not BIOS etc., right?

I'm still trying to find one common indicator between those models that share the same ME version. Maybe the chipset name? If so, we could create a folder based on that, e.g. "Q45 ME-AMT". But I'm unsure if this would be easily understand for the operators.

**Comment by texhex** [comment]
I just create issue #72 to discuss this after your vacation.

**Comment by texhex** [comment]
@datagutten For your information, all HP ProBook 4x0 G4  devices were using a custom TPM-BIOS-Settings.txt file while the one in \Shared\HP ProBook 4x0 G4\TPM-BIOS-Settings.txt contained the same settings. I guess this was remnants of your tests, so I changed that that all use the shared file.

**Pull request merged**
